---
- name: Configuration Drift Detection
  hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Load Configuration Maps based on groups
      include_vars:
        file: "config_maps/{{ item }}.yml"
      loop: "{{ group_names }}"
      ignore_errors: true # Ignore groups that don't have a corresponding config file

    - name: Safety Check for Auto-Fix
      block:
        - name: Warn user about Auto-Fix danger
          pause:
            prompt: |
              
              🚨 DANGER ZONE 🚨
              You have enabled --auto-fix. This will OVERWRITE configuration files on ALL target servers.
              Any manual changes will be lost permanently.
              
              Type 'yes' to confirm and proceed:
          register: confirmation
          run_once: true
        
        - name: Abort if not confirmed
          fail:
            msg: "Auto-fix aborted. You must type 'yes' to proceed."
          when: confirmation.user_input != 'yes'
          run_once: true
      when: auto_fix | default(false) | bool

  roles:
    # Removed role call

  tasks:
    - name: Audit all defined configuration files
      include_tasks: tasks/audit_file.yml
      loop: "{{ audit_files }}"
      loop_control:
        loop_var: audit_item
      when: audit_files is defined
